ci(release): Generate a fake semver for publishing to FlakeHub

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -56,9 +56,21 @@ jobs:
 
     - uses: cachix/install-nix-action@v23
 
+    - name: Determine the version
+      id: semver
+      run: |
+        tag="${{ inputs.release-tag || github.ref_name }}"
+        if [[ $tag =~ r([[:digit:]]{8}) ]]
+        then
+          echo "version=0.1.${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
+        else
+          echo "Failed to match against the tag: $tag" >&2
+          exit 1
+        fi
+
     - name: Push to flakehub
       uses: determinatesystems/flakehub-push@main
       with:
         visibility: "public"
         name: "akirak/emacs-config"
-        tag: "${{ inputs.release-tag }}"
+        tag: "${{ steps.semver.outputs.version }}"
